name = "navsphere"
compatibility_date = "2024-01-01"

[build]
command = "pnpm build"

[env.production]
GITHUB_ID = ""
GITHUB_SECRET = ""
GITHUB_OWNER = ""
GITHUB_REPO = ""
GITHUB_BRANCH = "main"
NEXTAUTH_SECRET = ""
